spring:
  profiles:
    active: local
    include: auth
---
spring:
  config:
    activate:
      on-profile: local

  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader = Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

