spring:
  profiles:
    active: local
    include: auth
---
spring:
  config:
    activate:
      on-profile: local

  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader = Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: "http://localhost:3000, http://localhost:3001"
            allowed-headers: "*"
            allowed-methods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://15.165.2.133:8761/eureka # AWS Discovery Service

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus
